### ISSUE TITLE
Allow subdomains when using localhost

### ISSUE THREAD

**Issue by adlerfaulkner** [CommunitySolidServer/access-token-verifier#142]
I am creating an IDP that is at a subdomain from my TLD using Community Solid Server. I am running into an error when attempting to use Solid Apps with a local version of the server that I have running on localhost.  
```
SecureUriClaimVerificationError: The URI claim could not be verified as secure.
Actual: http://adlerfaulkner.localhost:3000/profile/card#me
Expected: The webid claim to be an HTTPS URI or a localhost with port number HTTP URI
    at verifySecureUriClaim (/Users/adlerfaulkner/community-server/node_modules/@solid/access-token-verifier/dist/algorithm/verifySecureUriClaim.js:15:15)
    at verifySolidAccessToken (/Users/adlerfaulkner/community-server/node_modules/@solid/access-token-verifier/dist/algorithm/verifySolidAccessToken.js:32:53)
    at SolidTokenVerifier.verify (/Users/adlerfaulkner/community-server/node_modules/@solid/access-token-verifier/dist/class/SolidTokenVerifier.js:25:68)
    at DPoPWebIdExtractor.handle (/Users/adlerfaulkner/community-server/dist/authentication/DPoPWebIdExtractor.js:43:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-05-10T05:59:42.131Z [DPoPWebIdExtractor] warn: Error verifying WebID via DPoP-bound access token: The URI claim could not be verified as secure.
```

It comes from this line: 
https://github.com/CommunitySolidServer/access-token-verifier/blob/aca8f72a1b9d8beae75a7f3c4e6db3a33f530722/src/algorithm/verifySecureUriClaim.ts#L12

Would love to change the second clause of this line to allow for subdomains of localhost. I can create a PR for it soon.

**Comment by adlerfaulkner** [comment]
Closing in favor of using https
